export const ACTION_TYPES = {
    FETCH_JOBS: 'FETCH_JOBS',
    FETCH_JOBS_PENDING: 'FETCH_JOBS_PENDING',
    FETCH_JOBS_FULFILLED: 'FETCH_JOBS_FULFILLED',
    FETCH_JOBS_REJECTED: 'FETCH_JOBS_REJECTED',
    FETCH_JOB: 'FETCH_JOB',
    FETCH_JOB_PENDING: 'FETCH_JOB_PENDING',
    FETCH_JOB_FULFILLED: 'FETCH_JOB_FULFILLED',
    FETCH_JOB_REJECTED: 'FETCH_JOB_REJECTED',
};